server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
spring:
  application:
    name: user-consumer
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000 # 设置hystrix的超时时间为6000ms
feign:
  hystrix:
    enabled: true
  compression:
    request:
      enabled: true
    response:
      enabled: true
logging:
  level:
    com.baidu.service: debug