server:
  port: 10010
spring:
  application:
    name: api-gateway
zuul:
  routes:
    user-service: /user-service/**
  prefix: /api
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5